### PR TITLE
replaced libra_swarm with libra-swarm for guides and references

### PR DESCRIPTION
**Pull request by dmi3coder**
## Motivation

Due to different package name guides are not working with `libra_swarm`, correct name is `libra-swarm`

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/website/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

No tests required

## Related PRs

Haven't found any

### CODE REVIEW

**Comment by dmi3coder** [comment]
I've signed and sent CLA

**Comment by bmwill** [comment]
@ericnakagawa Can we get this reviewed and landed?

**Comment by ericnakagawa** [comment]
@dmi3coder Hi Dmitry, your CLA was not received. Can you resend to cla@libra.org?

**Comment by dmi3coder** [comment]
@ericnakagawa I re-sent it two days ago, let me know if there's still issues with it

**Comment by ericnakagawa** [comment]
@dmi3coder Received. Thanks for your contribution.

**Pull request merged**
