### PR TITLE
Fixed the ordering of steps for 'My First Transaction' instructions.

### PR DESCRIPTION
**Pull request by JoshLind**
## Motivation

Fix the ordering of instructions for users when following the 'My First Transaction' blogpost. At present, after the repo is cloned, the instructions say to change branch, however, you need to 'cd' into the repo before you can do that.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/website/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

Visual inspection: generate the site locally using scripts/build_docs.sh and review the "Life of a Transaction" page.

## Related PRs

None.

### CODE REVIEW

**Comment by JoshLind** [comment]
Please hold off reviewing this until I can sign the CLA, and further update the file to make the directory change more explicit.

**Comment by JoshLind** [comment]
I've signed the CLA and made some minor consistency amendments to the pull request commit. Waiting for review.

**Comment by JoshLind** [comment]
David, this is a random PR I made last week that improves the website blogpost with a fix. I wasn't sure who to assign it to!

**Comment by JoelMarcey** [comment]
This has been fixed via another commit. Thank you for submitting the PR.

https://github.com/libra/website/commit/246be4e39b054cc61192fea0d9a33b5a2adaff77

**Pull request closed without merging**
