### PR TITLE
Update testnet_waypoint.txt

### PR DESCRIPTION
**Pull request by mgorven**
This is super annoying...

### CODE REVIEW

**Comment by sherry-x** [comment]
Also we don't have permission to merge PR in this repo :(

**Comment by zekun000** [comment]
I know it's annoying :(

**Comment by dmitri-perelman** [comment]
Well, it's a real change in genesis: we can either say that clients are allowed to start from whatever genesis they're given, or we must update it every time genesis change...

**Comment by mgorven** [comment]
> Well, it's a real change in genesis: we can either say that clients are allowed to start from whatever genesis they're given, or we must update it every time genesis change...

The client behaviour is fine, but the deployment could be better. JSON-RPC could have an endpoint which serves the waypoint (which gets disabled in prod). Or Terraform could get the waypoint (some how) and upload to an S3 bucket with public read access so it happens automatically.

**Pull request merged**
